title: DjangoCon US
url: "https://2022.djangocon.us"
author : DjangoCon US
description: |
  DjangoCon US 2022 conference will take place in San Diego, California
  from October 16-21, 2022!
enforce_ssl: "2022.djangocon.us"
relative_permalinks: false
permalink: news/:title/  # permalink: date
timezone: America/Chicago
conf_year: 2022

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .cache
  - .editorconfig
  - .gitignore
  - .vendor
  - bin
  - bower_components
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docker-compose.yml
  - EDITORS_GUIDE.md
  - Gemfile
  - Gemfile.lock
  - justfile
  - LICENSE
  - Makefile
  - node_modules
  - NOTES.md
  - package*.json
  - Procfile
  - Rakefile
  - README.md
  - vendor
  - webpack.config.js

# We need `future` to allow our schedule to work :/
future: true

collections:  # process the _data folder
  components:
    output: false
  schedule:
    output: true
    permalink: /:collection/:name/
  organizers:
    output: false
    permalink: /:collection/
  presenters:
    output: true
    permalink: /:collection/
  sponsors:
    output: false
    permalink: /:collection/
  places:
    output: false
    permalink: /:collection/
  jobs:
    output: true
    permalink: /:collection/:name/

# SEO Plugin settings

twitter:
  username: djangocon

# This is the default logo that people see with opengraph
# logo: /static/2022-logos/squares-and-social/djangocon-square.png
logo: /static/img/social/og.png


# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/img/social/avatar-main.png
  - scope:
      path: "_presenters"
      type: presenters
    values:
      sitemap: false

# Our DjangoCon US settings...
conduct_email: "conduct@djangocon.us"
contact_us_email: "hello@djangocon.us"
opportunity_grants_email: "grants@djangocon.us"
program_team_email: "program@djangocon.us"
sponsors_email: "sponsors@djangocon.us"
visa_email: "visas@djangocon.us"

# Our DjangoCon US links
cfp_application: "https://pretalx.com/djangocon-2022/cfp"
hotel_reservation_link: "https://www.marriott.com/events/start.mi?id=1642551494496&key=GRP"
opportunity_grant_application: "https://docs.google.com/forms/d/1yc1HqqcJwi669vxTTs1daJbTeiNYwqM2h3gIgqbpWVE/viewform"
slack_link: ""
sponsorship_prospectus: ""
ticket_link: "https://ti.to/defna/djangocon-us-2022"
# youtube_link: ""

github: [metadata]
facebook:
  app_id: 280981518972848
